name: maths_quiz
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  


  cupertino_icons: ^1.0.6
  
dependency_overrides:
  uuid: ^4.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/images/backweb.jpg
    - assets/images/background.jpeg
    - assets/images/home page.jpeg
    - assets/images/background2.png
    - assets/audio/correct.wav
    - assets/audio/wrong.mp3
    


